#spring:
#  task:
#    execution:
#      pool:
#        core-size: 100 # 토비님 강의 따라하면서 worker 쓰레드를 100로 해야 동일한 결과가 나옴.

#server:
#  tomcat:
#    threads:
#      max: 1
spring:
  profiles:
    include:
      - h2

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # show_parameter_value
