spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # Remove comments if want to use schema.sql
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true # default = false
      path: /h2-console
      settings:
        trace: false # prevent trace out
        web-allow-others: false
