---
spring:
  config:
    activate:
      on-profile: test

  kafka:
    jack:
      bootstrap-servers: "localhost:1234"
      authentication:
        username: "jack"
        password: "jack"
        topics:
          jack-topic: "jack"
