---
spring:
  profiles:
    include:
      - jack-prod
      - jack-dev
  kafka:
    jack:
      bootstrap-servers: "localhost:52632"
      authentication:
        username: "jack"
        password: "jack"
        topics:
          jack-topic: "jack"
#  jpa:
#    hibernate:
#      ddl-auto: none # Remove comments if you want to use schema.sql and data.sql
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: test

  kafka:
    jack:
      bootstrap-servers: "localhost:52632"
      authentication:
        username: "jack"
        password: "jack"
        topics:
          jack-topic: "jack"
