spring:
  profiles:
    include:
      - jack-prod
      - jack-dev
      - rabbitmq
  kafka:
    jack:
      bootstrap-servers: "localhost:52632"
      authentication:
        username: "jack"
        password: "jack"
        topics:
          jack-topic: "jack"
#  jpa:
#    hibernate:
#      ddl-auto: none # Remove comments if you want to use schema.sql and data.sql
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=DB2;
  batch:
    job:
      enabled: false
  task:
    execution:
      pool:
        core-size: 100 # 토비님 강의 따라하면서 worker 쓰레드를 100로 해야 동일한 결과가 나옴.

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # show_parameter_value
server:
  tomcat:
    threads:
      max: 20


---
spring:
  config:
    activate:
      on-profile: test

  kafka:
    jack:
      bootstrap-servers: "localhost:52632"
      authentication:
        username: "jack"
        password: "jack"
        topics:
          jack-topic: "jack"
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        auto-startup: false # for testing
