---
spring:
  kafka:
    jack:
      bootstrap-servers: "localhost:52632"
      authentication:
        username: "jack"
        password: "jack"
        topics:
          jack-topic: "jack"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
---
spring:
  config:
    activate:
      on-profile: test

  kafka:
    jack:
      bootstrap-servers: "localhost:52632"
      authentication:
        username: "jack"
        password: "jack"
        topics:
          jack-topic: "jack"
