spring:
  profiles:
    include:
      - jdbc
  batch:
    job:
      enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: none # Remove comments if you want to use schema.sql and data.sql
#server:
#  servlet:
#    encoding:
#      charset: UTF-8 # Set charset

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # show_parameter_value
