spring:
  shard-datasource:
    username: main-jack
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    ddl-auto: validate
    type: child
    main:
      shards:
        - name: SHARD-00
          url: jdbc:mysql://localhost:3307/shard00
        - name: SHARD-01
          url: jdbc:mysql://localhost:3307/shard01
        - name: SHARD-02
          url: jdbc:mysql://localhost:3307/shard02
    child:
      shards:
        - name: SHARD-00
          url: jdbc:mysql://localhost:3308/shard00
        - name: SHARD-01
          url: jdbc:mysql://localhost:3308/shard01
        - name: SHARD-02
          url: jdbc:mysql://localhost:3308/shard02

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    open-in-view: false

sharding:
  strategy: MODULAR
  rule:
    mod: 3
