spring:
  shard-datasource:
    username: main-jack
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    ddl-auto: validate
    main:
      ## TODO(jack.comeback) : database 지정 필요
      shards:
        - name: SHARD-00
          url: jdbc:mysql://localhost:3307
        - name: SHARD-01
          url: jdbc:mysql://localhost:3307
        - name: SHARD-02
          url: jdbc:mysql://localhost:3307
    child:
      shards:
        - name: SHARD-00
          url: jdbc:mysql://localhost:3308
        - name: SHARD-01
          url: jdbc:mysql://localhost:3308
        - name: SHARD-02
          url: jdbc:mysql://localhost:3308

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    open-in-view: false

sharding:
  strategy: MODULAR
  rule:
    mod: 3
