spring:
  profiles:
    include:
      - jack-prod
      - jack-dev
      - h2
  batch:
    job:
      enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: none # Remove comments if you want to use schema.sql and data.sql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # show_parameter_value
