spring:
  rabbitmq:
    username: guest
    password: guest
    virtual-host: /
    host: localhost
    new:
      port: 5673
    old:
      port: 5672
    listener:
      direct:
        auto-startup: false # for testing
