spring:
  profiles:
    include:
      - rabbitmq
      - kafka
#  jpa:
#    hibernate:
#      ddl-auto: none # Remove comments if you want to use schema.sql and data.sql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # show_parameter_value

---
spring:
  config:
    activate:
      on-profile: test

  kafka:
    jack:
      bootstrap-servers: "localhost:52632"
      authentication:
        username: "jack"
        password: "jack"
        topics:
          jack-topic: "jack"
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        auto-startup: false # for testing
